name: rivo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  hooks_riverpod: ^2.4.10
  go_router: ^13.1.0
  dio: ^5.4.3
  formz: ^0.6.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.4.2
  path_provider: ^2.1.2
  app_links: ^3.3.0

  # ðŸ‘‡ Local supabase_flutter path (we'll prepare this folder in the next steps)
  #supabase_flutter:
   # path: local_packages/supabase_flutter

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
