name: rivo_app_beta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies: 
  dotted_border: ^3.1.0
  device_info_plus: ^9.1.1
  flutter_image_compress: ^2.1.0
  mime: ^1.0.4
  result_dart: ^1.1.0
  video_compress: ^3.1.4
  image: ^4.0.17
  image_picker: ^1.1.0
  flutter_hooks: ^0.20.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  photo_manager: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0 
  uuid: ^4.1.0
  equatable: ^2.0.5
  video_player: ^2.7.0
  flutter_riverpod: ^2.5.1
  dartz: ^0.10.1
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter 
  device_preview: ^1.1.0  
  permission_handler: ^11.0.1 

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  hooks_riverpod: ^2.4.10
  reorderable_grid_view: ^2.2.6
  go_router: ^16.0.0
  dio: ^5.4.3
  formz: ^0.8.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.4.2
  path_provider: ^2.1.2
  app_links: ^6.4.0
  glass_kit: ^4.0.1
  photo_manager_image_provider: ^2.2.0

  
  #supabase_flutter:
   # path: local_packages/supabase_flutter

dev_dependencies:
  riverpod_annotation: ^2.1.1
  build_runner: ^2.4.5
  freezed: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf  
    - family: NotoSansHebrew
      fonts:
        - asset: assets/fonts/NotoSansHebrew-Regular.ttf    
dependency_overrides:
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
